### PR TITLE
Gui

### PR DESCRIPTION
**Pull request by adrianblancode**
Lots of things for a very very preliminary GUI. The fonts have all been changed, the title screen now has shaders, the team play screen has background particles and control icons among other things.

### CODE REVIEW

**Comment by lemoele** [comment]
Seems good. I think we can merge.
But why did you delete the level count and line count though ?

**Comment by adrianblancode** [comment]
There wasn't much space to have all the text for both teams. I thought we could use your code to show when a team levels up instead :)

**Comment by lemoele** [comment]
OK then :) let's merge, I think the others are not working on this files ?

**Comment by adrianblancode** [comment]
Awesome :) Yeah I think the others don't use the scenes atm

**Pull request merged**
