### PR TITLE
3d gameboard

### PR DESCRIPTION
**Pull request by vhung92**
Master-slave controllers / gameboards have been integrated with the teamplay scene

### CODE REVIEW

**Comment by adrianblancode** [comment]
Left board reaches game over instantly, right gameboard the block falls however when it reaches the bottom it can still be moved and no further blocks spawn

**Comment by vhung92** [comment]
Are the tags set properly?

**Comment by adrianblancode** [comment]
It seems so. However I noticed something weird. Gameboard1 has an untagged spawner, Gameboard2 has a tagged spawner with no spawner script, then there is outside everything a third untagged spawner. Did you save the scene?

**Comment by vhung92** [comment]
Hm, the untagged spawner should not be there, the spawner for GameBoard2 should be untagged and not have a script

**Comment by adrianblancode** [comment]
The problem was that the third spawner should not have been there, and the blockcontroller didn't have the score text set. Committing now. 

There's also a few issues I'm just writing here for future reference that can be fixed later. There are desyncs with fall speed where one board will have their block lower, the left board updates position of the block faster so rapid movements will update slower on right board leading to blocks being in different positions in different boards.

**Comment by adrianblancode** [comment]
Check if it works on your computer, then you can merge :)

**Comment by vhung92** [comment]
I'll look into the desyncing in the future, merging for now

**Pull request merged**
