### PR TITLE
Improve grid

### PR DESCRIPTION
**Pull request by vhung92**
Grid and BlockController improvements. No longer dependant on having the gameboard at an exact location

### CODE REVIEW

**Comment by adrianblancode** [comment]
No blocks are spawning. Did you change something in the scene and forget to save it?

`UnassignedReferenceException: The variable currentBlock of BlockController has not been assigned. You probably need to assign the currentBlock variable of the BlockController script in the inspector. BlockController.isValidGridPos () (at Assets/Scripts/BlockController.cs:260)
BlockController.Update () (at Assets/Scripts/BlockController.cs:105)`

**Comment by vhung92** [comment]
Didn't change the scene at all, the variable currentBlock is assigned from the Spawner, so if you changed anything there it breaks. My version works so I don't know whats wrong

**Comment by adrianblancode** [comment]
I just saw there was an error at the top, which stated that it couldn't find any object with the tag "Team1_GameBoard". When I set the tag on the GameBoard object inside the editor, the blocks spawned but didn't move. So there probably has to be something in the scene itself

`gameBoard = GameObject.FindGameObjectWithTag ("Team1_GameBoard");`

**Comment by vhung92** [comment]
Right, always forgetting that Unity is not autosaving. 

Setting the `Team1_GameBoard` tag should resolve the issue, I saved my scene and those are the only changes I can see. I can push these changes and see if it fixes it.

**Comment by adrianblancode** [comment]
Allright, it seems to work now :) Merging

**Pull request merged**
